# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_acercade_regcontacto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acercade',
            new_name='Info_acerca',
        ),
        migrations.RenameModel(
            old_name='RegContacto',
            new_name='Info_contacto',
        ),
    ]
